# .rubocop.yml

# General settings
AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/**/*'

# Requires rubocop-performance and rubocop-rails for performance and Rails-related cops
require:
  - rubocop-performance
  - rubocop-rails

# Performance cops
Performance/FlatMap:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

# Rails-specific settings
Rails/AssertNot:
  Include:
    - '**/test/**/*'

Rails/RefuteMethods:
  Include:
    - '**/test/**/*'

# Style guidelines
Style/AndOr:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

# Layout/Indentation rules
Layout/IndentationStyle:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

# Lint settings
Lint/RedundantStringCoercion:
  Enabled: true

# Miscellaneous settings
Style/RedundantPercentQ:
  Enabled: true
Style/ColonMethodCall:
  Enabled: true

# Ensuring consistent method definition parentheses and avoiding unnecessary returns
Style/DefWithParentheses:
  Enabled: true
Style/MethodDefParentheses:
  Enabled: true
Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

# Aligning and formatting rules for comments and code blocks
Layout/CommentIndentation:
  Enabled: true
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
Layout/SpaceAfterComma:
  Enabled: true
Layout/SpaceBeforeComma:
  Enabled: true
Layout/SpaceBeforeFirstArg:
  Enabled: true
Layout/FirstParameterIndentation:
  Enabled: true

# Use Ruby >= 1.9 hash syntax
Style/HashSyntax:
  Enabled: true

# Disallowing hard tabs and trailing whitespace
Layout/IndentationStyle:
  Enabled: true
Layout/TrailingWhitespace:
  Enabled: true

# Forcing proper parentheses usage in method calls
Lint/RequireParentheses:
  Enabled: true
